### PR TITLE
Gogo/5 add test command

### PR DESCRIPTION
**Pull request by gogo2464**

### CODE REVIEW

**Comment by gogo2464** [comment]
This way to solve conflict: https://github.com/rust-console/cargo-n64/pull/9/commits/47251174db1db57a2c2282a3b3aad12e958bbda3 is wrong.

Everything else is good.

**Comment by parasyte** [comment]
Thank you for the PR!

The build is failing with `fmt` and `clippy` errors. These are both easy to fix. Here's how:

1. Install the `rustfmt` and `clippy` components

```bash
rustup add component rustfmt
rustup add component clippy
```

2. Run `cargo fix -Z unstable-options --clippy`

3. Run `cargo fmt --all`

4. Commit the updated files

After the build is passing, I will review the code.

**Comment by parasyte** [comment]
Going to close this because it is out of date with the main branch, and a lot of work is needed to run tests (e.g. on an emulator or N64 hardware).

**Comment by gogo2464** [comment]
@parasyte I am really really busy these time. I will need a lot of time but I would like to open again this issue latter.

**Pull request closed without merging**
